# Generated by Django 3.0.2 on 2020-05-11 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, help_text='课程名称', verbose_name='名称')),
                ('introduction', models.TextField( help_text='课程简介', verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6,  help_text='课程价格', verbose_name='价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              help_text='课程讲师', verbose_name='讲师')),
            ],
            options={'ordering': ('price',), 'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
    ]
